-- Migration: d5f3a62aad85

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION core.gen_project_id()
RETURNS varchar(10)
LANGUAGE sql
VOLATILE
AS $$
    SELECT encode(gen_random_bytes(5), 'hex');
$$;

CREATE OR REPLACE FUNCTION core.gen_resource_id()
RETURNS varchar(12)
LANGUAGE sql
VOLATILE
AS $$
    SELECT encode(gen_random_bytes(6), 'hex');
$$;


CREATE TABLE IF NOT EXISTS core.plans (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    is_public BOOLEAN DEFAULT false NOT NULL,
    is_available BOOLEAN DEFAULT true NOT NULL,
    db_limit INTEGER NOT NULL,
    secret_limit INTEGER NOT NULL,
    project_limit INTEGER NOT NULL,
    group_limit INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_plans PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS core.user_plans (
    user_id UUID NOT NULL,
    plan_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_user_plans PRIMARY KEY (user_id, plan_id),
    CONSTRAINT fk_user_plans_plan_id_plans FOREIGN KEY (plan_id) REFERENCES core.plans (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS core.projects (
    id VARCHAR(10) DEFAULT core.gen_project_id() NOT NULL,
    user_id UUID NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT ck_projects_ck_proj_id_hex CHECK (id ~ '^[0-9a-f]{10}$'), 
    CONSTRAINT uq_projects_user_id_name UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS core.resources (
    id VARCHAR(12) DEFAULT core.gen_resource_id() NOT NULL,
    project_id VARCHAR(10) NOT NULL,
    kind VARCHAR(16) NOT NULL
        CHECK (kind IN ('database', 'secret')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_resources PRIMARY KEY (id),
    CONSTRAINT ck_resources_ck_res_id_hex CHECK (id ~ '^[0-9a-f]{12}$'), 
    CONSTRAINT fk_resources_proj_id_projects FOREIGN KEY (project_id) REFERENCES core.projects (id) ON DELETE CASCADE,
    CONSTRAINT uq_resources_id_project_id UNIQUE (id, project_id)
);

CREATE TABLE IF NOT EXISTS core.resource_states (
    resource_id VARCHAR(12) NOT NULL,
    runtime_state VARCHAR(16) NOT NULL
        CHECK (runtime_state IN ('creating', 'available', 'stopping', 'stopped', 'starting', 'deleting', 'deleted', 'failed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_resource_states PRIMARY KEY (resource_id),
    CONSTRAINT fk_resource_states_res_id_resources FOREIGN KEY (resource_id) REFERENCES core.resources (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS core.tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id VARCHAR(10) NOT NULL,
    tag_key VARCHAR NOT NULL,
    tag_value VARCHAR NOT NULL,
    color VARCHAR,
    is_system BOOLEAN DEFAULT false NOT NULL,
    is_readonly BOOLEAN DEFAULT false NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT fk_tags_project_id_projects FOREIGN KEY (project_id) REFERENCES core.projects (id) ON DELETE CASCADE,
    CONSTRAINT uq_tags_id_project_id UNIQUE (id, project_id),
    CONSTRAINT uq_tags_proj_id_tag_key_tag_value UNIQUE (project_id, tag_key, tag_value)
);

CREATE TABLE IF NOT EXISTS core.resource_tags (
    tag_id BIGINT NOT NULL,
    project_id VARCHAR(10) NOT NULL,
    resource_id VARCHAR(12) NOT NULL,
    CONSTRAINT pk_resource_tags PRIMARY KEY (project_id, resource_id, tag_id),
    CONSTRAINT fk_resource_tags_res_id_resources FOREIGN KEY (resource_id, project_id) REFERENCES core.resources (id, project_id) ON DELETE CASCADE,
    CONSTRAINT fk_resource_tags_tag_id_tags FOREIGN KEY (tag_id, project_id) REFERENCES core.tags (id, project_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS core.secrets (
    project_id VARCHAR(10) NOT NULL,
    resource_id VARCHAR(12) NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    secret_value_hash VARCHAR NOT NULL,
    version INTEGER DEFAULT 1 NOT NULL,
    revealed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_secrets PRIMARY KEY (resource_id),
    CONSTRAINT fk_secrets_res_id_resources FOREIGN KEY (resource_id) REFERENCES core.resources (id) ON DELETE CASCADE,
    CONSTRAINT fk_secrets_res_id_proj_id_resources FOREIGN KEY (resource_id, project_id) REFERENCES core.resources (id, project_id) ON DELETE CASCADE,
    CONSTRAINT uq_secrets_proj_id_name UNIQUE (project_id, name)
);

CREATE TABLE IF NOT EXISTS core.dbs (
    project_id VARCHAR(10) NOT NULL,
    resource_id VARCHAR(12) NOT NULL,
    name VARCHAR NOT NULL,
    normalized_name VARCHAR NOT NULL,
    desired_runtime_state VARCHAR(16) NOT NULL
        CHECK (desired_runtime_state IN ('running', 'suspended', 'terminated')),
    description VARCHAR,
    CONSTRAINT pk_dbs PRIMARY KEY (resource_id),
    CONSTRAINT fk_dbs_res_id_resources FOREIGN KEY (resource_id) REFERENCES core.resources (id) ON DELETE CASCADE,
    CONSTRAINT fk_dbs_res_id_proj_id_resources FOREIGN KEY (resource_id, project_id) REFERENCES core.resources (id, project_id) ON DELETE CASCADE,
    CONSTRAINT uq_dbs_proj_id_normalized_name UNIQUE (project_id, normalized_name)
);

CREATE TABLE IF NOT EXISTS core.db_verifiers (
    project_id VARCHAR(10) NOT NULL,
    db_id VARCHAR(12) NOT NULL,
    password_secret_id VARCHAR(12) NOT NULL,
    password_verifier VARCHAR NOT NULL,
    password_version INTEGER NOT NULL,
    CONSTRAINT pk_db_verifiers PRIMARY KEY (db_id, password_secret_id),
    CONSTRAINT fk_db_verifiers_db_id_dbs FOREIGN KEY (db_id) REFERENCES core.dbs (resource_id) ON DELETE CASCADE,
    CONSTRAINT fk_db_verifiers_password_secret_id_secrets FOREIGN KEY (password_secret_id) REFERENCES core.secrets (resource_id) ON DELETE CASCADE,
    CONSTRAINT fk_db_verifiers_db_id_project_id_resources FOREIGN KEY (db_id, project_id) REFERENCES core.resources (id, project_id) ON DELETE CASCADE,
    CONSTRAINT fk_db_verifiers_pass_sec_id_proj_id_resources FOREIGN KEY (password_secret_id, project_id) REFERENCES core.resources (id, project_id) ON DELETE CASCADE
);


WITH updated AS (
    UPDATE core.version_platform
    SET version_num = 'd5f3a62aad85'
    RETURNING core.version_platform.version_num
)
INSERT INTO core.version_platform (version_num)
SELECT 'd5f3a62aad85'
WHERE NOT EXISTS (SELECT 1 FROM updated)
RETURNING core.version_platform.version_num;

COMMIT;
