BEGIN;

CREATE TABLE IF NOT EXISTS version_platform (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT version_platform_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 1528642f5b46

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION gen_project_id()
RETURNS varchar(10)
LANGUAGE sql
VOLATILE
AS $$
    SELECT encode(gen_random_bytes(5), 'hex');
$$;

CREATE OR REPLACE FUNCTION gen_resource_id()
RETURNS varchar(12)
LANGUAGE sql
VOLATILE
AS $$
    SELECT encode(gen_random_bytes(6), 'hex');
$$;


CREATE TABLE IF NOT EXISTS plans (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    is_public BOOLEAN DEFAULT false NOT NULL,
    is_available BOOLEAN DEFAULT true NOT NULL,
    db_limit INTEGER NOT NULL,
    code_limit INTEGER NOT NULL,
    function_limit INTEGER NOT NULL,
    secret_limit INTEGER NOT NULL,
    project_limit INTEGER NOT NULL,
    group_limit INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_plans PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_plans (
    user_id UUID NOT NULL,
    plan_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_user_plans PRIMARY KEY (user_id, plan_id),
    CONSTRAINT fk_user_plans_plan_id_plans FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS projects (
    id VARCHAR(10) DEFAULT gen_project_id() NOT NULL,
    user_id UUID NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT ck_projects_ck_projects_id_hex CHECK (id ~ '^[0-9a-f]{10}$'), 
    CONSTRAINT uq_projects_user_id_name UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS resources (
    id VARCHAR(12) DEFAULT gen_resource_id() NOT NULL,
    project_id VARCHAR(10) NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    resource_type VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_resources PRIMARY KEY (id),
    CONSTRAINT ck_resources_ck_resources_id_hex CHECK (id ~ '^[0-9a-f]{12}$'), 
    CONSTRAINT fk_resources_project_id_projects FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT uq_resources_id_project_id UNIQUE (id, project_id)
);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id VARCHAR(10) NOT NULL,
    tag_key VARCHAR NOT NULL,
    tag_value VARCHAR NOT NULL,
    color VARCHAR,
    is_system BOOLEAN DEFAULT false NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT fk_tags_project_id_projects FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT uq_tags_id_project_id UNIQUE (id, project_id),
    CONSTRAINT uq_tags_project_id_tag_key_tag_value UNIQUE (project_id, tag_key, tag_value)
);

CREATE TABLE IF NOT EXISTS resource_tags (
    tag_id BIGINT NOT NULL,
    project_id VARCHAR(10) NOT NULL,
    resource_id VARCHAR(12) NOT NULL,
    CONSTRAINT pk_resource_tags PRIMARY KEY (project_id, resource_id, tag_id),
    CONSTRAINT fk_resource_tags_resource_id_resources FOREIGN KEY (resource_id, project_id) REFERENCES resources (id, project_id) ON DELETE CASCADE,
    CONSTRAINT fk_resource_tags_tag_id_tags FOREIGN KEY (tag_id, project_id) REFERENCES tags (id, project_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS secrets (
    resource_id VARCHAR(12) NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    secret_value_hash VARCHAR NOT NULL,
    revealed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_secrets PRIMARY KEY (resource_id),
    CONSTRAINT fk_secrets_resource_id_resources FOREIGN KEY (resource_id) REFERENCES resources (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbs (
    resource_id VARCHAR(12) NOT NULL,
    name VARCHAR NOT NULL,
    normalized_name VARCHAR NOT NULL,
    description VARCHAR,
    next_table_id INTEGER DEFAULT 1 NOT NULL,
    CONSTRAINT pk_dbs PRIMARY KEY (resource_id),
    CONSTRAINT fk_dbs_resource_id_resources FOREIGN KEY (resource_id) REFERENCES resources (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS db_tables (
    id INTEGER NOT NULL,
    db_id VARCHAR(12) NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    next_column_id INTEGER DEFAULT 1 NOT NULL,
    CONSTRAINT pk_db_tables PRIMARY KEY (id, db_id),
    CONSTRAINT fk_db_tables_db_id_dbs FOREIGN KEY (db_id) REFERENCES dbs (resource_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_db_tables_db_id_name ON db_tables (db_id, name);

CREATE TABLE IF NOT EXISTS db_table_columns (
    id INTEGER NOT NULL,
    table_id INTEGER NOT NULL,
    db_id VARCHAR(12) NOT NULL,
    name VARCHAR NOT NULL,
    data_type VARCHAR NOT NULL,
    is_primary_key BOOLEAN DEFAULT false NOT NULL,
    is_nullable BOOLEAN DEFAULT false NOT NULL,
    is_unique BOOLEAN DEFAULT false NOT NULL,
    is_array BOOLEAN DEFAULT false NOT NULL,
    default_value VARCHAR,
    foreign_key VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_db_table_columns PRIMARY KEY (id, table_id, db_id),
    CONSTRAINT fk_db_table_columns_table_id_db_tables FOREIGN KEY (table_id, db_id) REFERENCES db_tables (id, db_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_db_table_columns_db_id_table_id_name ON db_table_columns (db_id, table_id, name);


INSERT INTO version_platform (version_num) VALUES ('1528642f5b46')
ON CONFLICT (version_num) DO NOTHING;

COMMIT;