services:
  drone-gc:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

    mem_limit: 128m
    cpus: "0.25"
    pids_limit: 32

    command: ["gc"]
